version: 0.2

phases:
  install:
    commands:
      - echo Installing Go dependencies
      - go mod download
  build:
    commands:
      - echo Building Go service
      - if go build ./...; then echo "BUILD_SUCCESS=true" >> build_status.txt; else echo "BUILD_SUCCESS=false" >> build_status.txt; fi

artifacts:
  files:
    - build_status.txt
